# coding: utf-8

"""
    BNG Bank - XS2A Interface 1.0

    <h1>Summary</h1>  <p>The <strong>BNG Bank - XS2A Interface</strong> <em>API</em>. This API enables European banking customers to benefit from innovative products and services ('Banking as a Service') by granting TPPs safe and secure (authenticated and authorised) access to their bank accounts and financial data.</p>  <p>The possible Approaches are:</p>  <ul>     <li>Redirect SCA OAuth Approach</li>  </ul>  <h2>Some General Remarks Related to this version of the specification:</h2>  <ul>     <li>        <p><strong>This API definition is based on the Implementation Guidelines of the Berlin Group PSD2 API.</strong>It is not an replacement in any sense. The main specification is (at the moment) always the Implementation Guidelines of the Berlin Group PSD2 API.</p>     </li>     <li>        <p><strong>This API definition contains the REST-API for requests from the TPP to the ASPSP.</strong></p>     </li>  </ul>  <h2>General Remarks on Data Types</h2>  <p>The Berlin Group definition of UTF-8 strings in context of the PSD2 API have to support at least the following characters</p>  <p>a b c d e f g h i j k l m n o p q r s t u v w x y z</p>  <p>A B C D E F G H I J K L M N O P Q R S T U V W X Y Z</p>  <p>0 1 2 3 4 5 6 7 8 9</p>  <p>/ - ? : ( ) . , ' +</p>  <p>Space</p>  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: 
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "swagger-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
    "certifi>=2017.4.17",
    "python-dateutil>=2.1",
    "six>=1.10",
    "urllib3>=1.23"
]
    

setup(
    name=NAME,
    version=VERSION,
    description="BNG Bank - XS2A Interface 1.0",
    author_email="",
    url="",
    keywords=["Swagger", "BNG Bank - XS2A Interface 1.0"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    &lt;h1&gt;Summary&lt;/h1&gt;  &lt;p&gt;The &lt;strong&gt;BNG Bank - XS2A Interface&lt;/strong&gt; &lt;em&gt;API&lt;/em&gt;. This API enables European banking customers to benefit from innovative products and services (&#39;Banking as a Service&#39;) by granting TPPs safe and secure (authenticated and authorised) access to their bank accounts and financial data.&lt;/p&gt;  &lt;p&gt;The possible Approaches are:&lt;/p&gt;  &lt;ul&gt;     &lt;li&gt;Redirect SCA OAuth Approach&lt;/li&gt;  &lt;/ul&gt;  &lt;h2&gt;Some General Remarks Related to this version of the specification:&lt;/h2&gt;  &lt;ul&gt;     &lt;li&gt;        &lt;p&gt;&lt;strong&gt;This API definition is based on the Implementation Guidelines of the Berlin Group PSD2 API.&lt;/strong&gt;It is not an replacement in any sense. The main specification is (at the moment) always the Implementation Guidelines of the Berlin Group PSD2 API.&lt;/p&gt;     &lt;/li&gt;     &lt;li&gt;        &lt;p&gt;&lt;strong&gt;This API definition contains the REST-API for requests from the TPP to the ASPSP.&lt;/strong&gt;&lt;/p&gt;     &lt;/li&gt;  &lt;/ul&gt;  &lt;h2&gt;General Remarks on Data Types&lt;/h2&gt;  &lt;p&gt;The Berlin Group definition of UTF-8 strings in context of the PSD2 API have to support at least the following characters&lt;/p&gt;  &lt;p&gt;a b c d e f g h i j k l m n o p q r s t u v w x y z&lt;/p&gt;  &lt;p&gt;A B C D E F G H I J K L M N O P Q R S T U V W X Y Z&lt;/p&gt;  &lt;p&gt;0 1 2 3 4 5 6 7 8 9&lt;/p&gt;  &lt;p&gt;/ - ? : ( ) . , &#39; +&lt;/p&gt;  &lt;p&gt;Space&lt;/p&gt;  # noqa: E501
    """
)
