# coding: utf-8

# flake8: noqa
"""
    BNG Bank - XS2A Interface 1.0

    <h1>Summary</h1>  <p>The <strong>BNG Bank - XS2A Interface</strong> <em>API</em>. This API enables European banking customers to benefit from innovative products and services ('Banking as a Service') by granting TPPs safe and secure (authenticated and authorised) access to their bank accounts and financial data.</p>  <p>The possible Approaches are:</p>  <ul>     <li>Redirect SCA OAuth Approach</li>  </ul>  <h2>Some General Remarks Related to this version of the specification:</h2>  <ul>     <li>        <p><strong>This API definition is based on the Implementation Guidelines of the Berlin Group PSD2 API.</strong>It is not an replacement in any sense. The main specification is (at the moment) always the Implementation Guidelines of the Berlin Group PSD2 API.</p>     </li>     <li>        <p><strong>This API definition contains the REST-API for requests from the TPP to the ASPSP.</strong></p>     </li>  </ul>  <h2>General Remarks on Data Types</h2>  <p>The Berlin Group definition of UTF-8 strings in context of the PSD2 API have to support at least the following characters</p>  <p>a b c d e f g h i j k l m n o p q r s t u v w x y z</p>  <p>A B C D E F G H I J K L M N O P Q R S T U V W X Y Z</p>  <p>0 1 2 3 4 5 6 7 8 9</p>  <p>/ - ? : ( ) . , ' +</p>  <p>Space</p>  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: 
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.account_access import AccountAccess
from swagger_client.models.account_consent_access import AccountConsentAccess
from swagger_client.models.account_consent_data import AccountConsentData
from swagger_client.models.account_details_dto import AccountDetailsDto
from swagger_client.models.account_dto import AccountDto
from swagger_client.models.account_reference_dto import AccountReferenceDto
from swagger_client.models.account_report_dto import AccountReportDto
from swagger_client.models.account_report_links_dto import AccountReportLinksDto
from swagger_client.models.add_bulk_payment_initiation_response_dto import AddBulkPaymentInitiationResponseDto
from swagger_client.models.add_bulk_payment_initiation_response_links_dto import AddBulkPaymentInitiationResponseLinksDto
from swagger_client.models.add_bulk_payment_initiation_response_payment_initiation_dto import AddBulkPaymentInitiationResponsePaymentInitiationDto
from swagger_client.models.add_consent_authorisation_response_dto import AddConsentAuthorisationResponseDto
from swagger_client.models.add_consent_authorisation_response_links_dto import AddConsentAuthorisationResponseLinksDto
from swagger_client.models.add_consent_response_dto import AddConsentResponseDto
from swagger_client.models.add_consent_response_links_dto import AddConsentResponseLinksDto
from swagger_client.models.add_payment_authorisation_response_dto import AddPaymentAuthorisationResponseDto
from swagger_client.models.add_payment_authorisation_response_links_dto import AddPaymentAuthorisationResponseLinksDto
from swagger_client.models.add_payment_initiation_response_dto import AddPaymentInitiationResponseDto
from swagger_client.models.add_payment_initiation_response_links_dto import AddPaymentInitiationResponseLinksDto
from swagger_client.models.address_dto import AddressDto
from swagger_client.models.amount_field_dto import AmountFieldDto
from swagger_client.models.api_error import ApiError
from swagger_client.models.balance_dto import BalanceDto
from swagger_client.models.confirmation_of_funds_consent_account import ConfirmationOfFundsConsentAccount
from swagger_client.models.confirmation_of_funds_consent_data import ConfirmationOfFundsConsentData
from swagger_client.models.cross_border_account_reference_dto import CrossBorderAccountReferenceDto
from swagger_client.models.cross_border_payment_dto import CrossBorderPaymentDto
from swagger_client.models.euro_amount_field_dto import EuroAmountFieldDto
from swagger_client.models.funds_confirmation_dto import FundsConfirmationDto
from swagger_client.models.funds_confirmation_response_dto import FundsConfirmationResponseDto
from swagger_client.models.get_consent_authorisation_response_dto import GetConsentAuthorisationResponseDto
from swagger_client.models.get_consent_authorisations_response_dto import GetConsentAuthorisationsResponseDto
from swagger_client.models.get_consent_status_response_dto import GetConsentStatusResponseDto
from swagger_client.models.get_payment_authorisation_response_dto import GetPaymentAuthorisationResponseDto
from swagger_client.models.get_payment_authorisations_response_dto import GetPaymentAuthorisationsResponseDto
from swagger_client.models.get_payment_initiation_for_bulk_payment_response_dto import GetPaymentInitiationForBulkPaymentResponseDto
from swagger_client.models.get_payment_initiation_for_cross_border_payment_response_dto import GetPaymentInitiationForCrossBorderPaymentResponseDto
from swagger_client.models.get_payment_initiation_response_dto import GetPaymentInitiationResponseDto
from swagger_client.models.get_payment_initiation_status_response_dto import GetPaymentInitiationStatusResponseDto
from swagger_client.models.href_type_dto import HrefTypeDto
from swagger_client.models.o_auth_meta_data_configuration_response_dto import OAuthMetaDataConfigurationResponseDto
from swagger_client.models.read_account_details_response_dto import ReadAccountDetailsResponseDto
from swagger_client.models.read_account_list_response_dto import ReadAccountListResponseDto
from swagger_client.models.read_account_list_response_links_dto import ReadAccountListResponseLinksDto
from swagger_client.models.read_balance_response_dto import ReadBalanceResponseDto
from swagger_client.models.read_transaction_details_response_dto import ReadTransactionDetailsResponseDto
from swagger_client.models.read_transactions_response_dto import ReadTransactionsResponseDto
from swagger_client.models.read_transactions_response_links_dto import ReadTransactionsResponseLinksDto
from swagger_client.models.remittance_dto import RemittanceDto
from swagger_client.models.report_exchange_rate_dto import ReportExchangeRateDto
from swagger_client.models.single_payment_dto import SinglePaymentDto
from swagger_client.models.token_response_dto import TokenResponseDto
from swagger_client.models.tpp_message_dto import TppMessageDto
from swagger_client.models.tpp_message_response_dto import TppMessageResponseDto
from swagger_client.models.transaction_dto import TransactionDto
from swagger_client.models.transaction_response_links_dto import TransactionResponseLinksDto
